tag @s add in_main
tag @s remove in_gear

scoreboard objectives remove gear_slot1
scoreboard objectives remove gear_slot2
scoreboard objectives remove gear_slot3
scoreboard objectives remove gear_slot4
scoreboard objectives remove gear_slot5
scoreboard objectives remove gear_slot6
scoreboard objectives remove gear_slot7
scoreboard objectives remove gear_slot8
scoreboard objectives remove gear_slot9
scoreboard objectives remove gear_slot10
scoreboard objectives remove gear_slot11
scoreboard objectives remove gear_slot12
scoreboard objectives remove gear_slot13
scoreboard objectives remove gear_slot14
scoreboard objectives remove gear_slot15
scoreboard objectives remove gear_slot16
scoreboard objectives remove gear_slot17
scoreboard objectives remove gear_slot18
scoreboard objectives remove gear_slot19
scoreboard objectives remove gear_slot20
scoreboard objectives remove gear_slot21
scoreboard objectives remove gear_slot22
scoreboard objectives remove gear_slot23
scoreboard objectives remove gear_slot24
scoreboard objectives remove left_arrow
scoreboard objectives remove right_arrow
scoreboard objectives remove equip_upgrade

scoreboard objectives remove gear_menu
scoreboard objectives remove gear_page
scoreboard objectives remove eq_menu