execute if score %pz pos matches 0..13 run data modify storage map player set value '[{"translate":"space.-1","font":"default"}]'
execute if score %pz pos matches 14..26 run data modify storage map player set value '[{"translate":"space.-2","font":"default"}]'
execute if score %pz pos matches 27..39 run data modify storage map player set value '[{"translate":"space.-3","font":"default"}]'
execute if score %pz pos matches 40..52 run data modify storage map player set value '[{"translate":"space.-4","font":"default"}]'
execute if score %pz pos matches 53..65 run data modify storage map player set value '[{"translate":"space.-5","font":"default"}]'
execute if score %pz pos matches 66..78 run data modify storage map player set value '[{"translate":"space.-6","font":"default"}]'
execute if score %pz pos matches 79..91 run data modify storage map player set value '[{"translate":"space.-7","font":"default"}]'