execute if score %pz pos matches 273..285 run data modify storage map player set value '[{"translate":"space.-22","font":"default"}]'
execute if score %pz pos matches 286..298 run data modify storage map player set value '[{"translate":"space.-23","font":"default"}]'
execute if score %pz pos matches 299..311 run data modify storage map player set value '[{"translate":"space.-24","font":"default"}]'
execute if score %pz pos matches 312..324 run data modify storage map player set value '[{"translate":"space.-25","font":"default"}]'
execute if score %pz pos matches 325..337 run data modify storage map player set value '[{"translate":"space.-26","font":"default"}]'
execute if score %pz pos matches 338..350 run data modify storage map player set value '[{"translate":"space.-27","font":"default"}]'
execute if score %pz pos matches 351..362 run data modify storage map player set value '[{"translate":"space.-28","font":"default"}]'