execute if score %pz pos matches 910..922 run data modify storage map player set value '[{"translate":"space.-71","font":"default"}]'
execute if score %pz pos matches 923..935 run data modify storage map player set value '[{"translate":"space.-72","font":"default"}]'
execute if score %pz pos matches 936..948 run data modify storage map player set value '[{"translate":"space.-73","font":"default"}]'
execute if score %pz pos matches 949..961 run data modify storage map player set value '[{"translate":"space.-74","font":"default"}]'
execute if score %pz pos matches 962..974 run data modify storage map player set value '[{"translate":"space.-75","font":"default"}]'
execute if score %pz pos matches 975..987 run data modify storage map player set value '[{"translate":"space.-76","font":"default"}]'
execute if score %pz pos matches 988..1000 run data modify storage map player set value '[{"translate":"space.-77","font":"default"}]'