execute if score %pz pos matches 92..104 run data modify storage map player set value '[{"translate":"space.-8","font":"default"}]'
execute if score %pz pos matches 105..117 run data modify storage map player set value '[{"translate":"space.-9","font":"default"}]'
execute if score %pz pos matches 118..130 run data modify storage map player set value '[{"translate":"space.-10","font":"default"}]'
execute if score %pz pos matches 131..143 run data modify storage map player set value '[{"translate":"space.-11","font":"default"}]'
execute if score %pz pos matches 144..156 run data modify storage map player set value '[{"translate":"space.-12","font":"default"}]'
execute if score %pz pos matches 157..169 run data modify storage map player set value '[{"translate":"space.-13","font":"default"}]'
execute if score %pz pos matches 170..182 run data modify storage map player set value '[{"translate":"space.-14","font":"default"}]'