execute if score @s gear_menu matches 1 unless score @s gear_slot1 matches 10000 run tag @s add equip_upgrade
execute if score @s gear_menu matches 2 unless score @s gear_slot2 matches 10000 run tag @s add equip_upgrade
execute if score @s gear_menu matches 3 unless score @s gear_slot3 matches 10000 run tag @s add equip_upgrade
execute if score @s gear_menu matches 4 unless score @s gear_slot4 matches 10000 run tag @s add equip_upgrade
execute if score @s gear_menu matches 5 unless score @s gear_slot5 matches 10000 run tag @s add equip_upgrade
execute if score @s gear_menu matches 6 unless score @s gear_slot6 matches 10000 run tag @s add equip_upgrade
execute if score @s gear_menu matches 7 unless score @s gear_slot7 matches 10000 run tag @s add equip_upgrade
execute if score @s gear_menu matches 8 unless score @s gear_slot8 matches 10000 run tag @s add equip_upgrade
execute if score @s gear_menu matches 9 unless score @s gear_slot9 matches 10000 run tag @s add equip_upgrade
execute if score @s gear_menu matches 10 unless score @s gear_slot10 matches 10000 run tag @s add equip_upgrade
execute if score @s gear_menu matches 11 unless score @s gear_slot11 matches 10000 run tag @s add equip_upgrade
execute if score @s gear_menu matches 12 unless score @s gear_slot12 matches 10000 run tag @s add equip_upgrade
execute if score @s gear_menu matches 13 unless score @s gear_slot13 matches 10000 run tag @s add equip_upgrade
execute if score @s gear_menu matches 14 unless score @s gear_slot14 matches 10000 run tag @s add equip_upgrade
execute if score @s gear_menu matches 15 unless score @s gear_slot15 matches 10000 run tag @s add equip_upgrade
execute if score @s gear_menu matches 16 unless score @s gear_slot16 matches 10000 run tag @s add equip_upgrade
execute if score @s gear_menu matches 17 unless score @s gear_slot17 matches 10000 run tag @s add equip_upgrade
execute if score @s gear_menu matches 18 unless score @s gear_slot18 matches 10000 run tag @s add equip_upgrade
execute if score @s gear_menu matches 19 unless score @s gear_slot19 matches 10000 run tag @s add equip_upgrade
execute if score @s gear_menu matches 20 unless score @s gear_slot20 matches 10000 run tag @s add equip_upgrade
execute if score @s gear_menu matches 21 unless score @s gear_slot21 matches 10000 run tag @s add equip_upgrade
execute if score @s gear_menu matches 22 unless score @s gear_slot22 matches 10000 run tag @s add equip_upgrade
execute if score @s gear_menu matches 23 unless score @s gear_slot23 matches 10000 run tag @s add equip_upgrade
execute if score @s gear_menu matches 24 unless score @s gear_slot24 matches 10000 run tag @s add equip_upgrade