execute if score %px pos matches 183..195 run data modify storage map player set value '[{"text":"\\uF80E","font":"maps"},{"translate":"space.-81","font":"default"}]'
execute if score %px pos matches 196..208 run data modify storage map player set value '[{"text":"\\uF80F","font":"maps"},{"translate":"space.-81","font":"default"}]'
execute if score %px pos matches 209..221 run data modify storage map player set value '[{"text":"\\uF810","font":"maps"},{"translate":"space.-81","font":"default"}]'
execute if score %px pos matches 222..234 run data modify storage map player set value '[{"text":"\\uF811","font":"maps"},{"translate":"space.-81","font":"default"}]'
execute if score %px pos matches 235..247 run data modify storage map player set value '[{"text":"\\uF812","font":"maps"},{"translate":"space.-81","font":"default"}]'
execute if score %px pos matches 248..260 run data modify storage map player set value '[{"text":"\\uF813","font":"maps"},{"translate":"space.-81","font":"default"}]'
execute if score %px pos matches 261..272 run data modify storage map player set value '[{"text":"\\uF814","font":"maps"},{"translate":"space.-81","font":"default"}]'