execute if score %px pos matches 363..375 run data modify storage map player set value '[{"text":"\\uF81C","font":"maps"},{"translate":"space.-81","font":"default"}]'
execute if score %px pos matches 376..388 run data modify storage map player set value '[{"text":"\\uF81D","font":"maps"},{"translate":"space.-81","font":"default"}]'
execute if score %px pos matches 389..401 run data modify storage map player set value '[{"text":"\\uF81E","font":"maps"},{"translate":"space.-81","font":"default"}]'
execute if score %px pos matches 402..414 run data modify storage map player set value '[{"text":"\\uF81F","font":"maps"},{"translate":"space.-81","font":"default"}]'
execute if score %px pos matches 415..427 run data modify storage map player set value '[{"text":"\\uF820","font":"maps"},{"translate":"space.-81","font":"default"}]'
execute if score %px pos matches 428..440 run data modify storage map player set value '[{"text":"\\uF821","font":"maps"},{"translate":"space.-81","font":"default"}]'
execute if score %px pos matches 441..454 run data modify storage map player set value '[{"text":"\\uF822","font":"maps"},{"translate":"space.-81","font":"default"}]'