execute if score %px pos matches 819..831 run data modify storage map player set value '[{"text":"\\uF83F","font":"maps"},{"translate":"space.-81","font":"default"}]'
execute if score %px pos matches 832..844 run data modify storage map player set value '[{"text":"\\uF840","font":"maps"},{"translate":"space.-81","font":"default"}]'
execute if score %px pos matches 845..857 run data modify storage map player set value '[{"text":"\\uF841","font":"maps"},{"translate":"space.-81","font":"default"}]'
execute if score %px pos matches 858..870 run data modify storage map player set value '[{"text":"\\uF842","font":"maps"},{"translate":"space.-81","font":"default"}]'
execute if score %px pos matches 871..883 run data modify storage map player set value '[{"text":"\\uF843","font":"maps"},{"translate":"space.-81","font":"default"}]'
execute if score %px pos matches 884..896 run data modify storage map player set value '[{"text":"\\uF844","font":"maps"},{"translate":"space.-81","font":"default"}]'
execute if score %px pos matches 897..909 run data modify storage map player set value '[{"text":"\\uF845","font":"maps"},{"translate":"space.-81","font":"default"}]'