execute if score %px pos matches 92..104 run data modify storage map player set value '[{"text":"\\uF807","font":"maps"},{"translate":"space.-81","font":"default"}]'
execute if score %px pos matches 105..117 run data modify storage map player set value '[{"text":"\\uF808","font":"maps"},{"translate":"space.-81","font":"default"}]'
execute if score %px pos matches 118..130 run data modify storage map player set value '[{"text":"\\uF809","font":"maps"},{"translate":"space.-81","font":"default"}]'
execute if score %px pos matches 131..143 run data modify storage map player set value '[{"text":"\\uF80A","font":"maps"},{"translate":"space.-81","font":"default"}]'
execute if score %px pos matches 144..156 run data modify storage map player set value '[{"text":"\\uF80B","font":"maps"},{"translate":"space.-81","font":"default"}]'
execute if score %px pos matches 157..169 run data modify storage map player set value '[{"text":"\\uF80C","font":"maps"},{"translate":"space.-81","font":"default"}]'
execute if score %px pos matches 170..182 run data modify storage map player set value '[{"text":"\\uF80D","font":"maps"},{"translate":"space.-81","font":"default"}]'