execute if score @s craft_slot_3 matches 0 run data merge block 0 2 0 {Text1:'[{"nbt":"Text1","block":"0 2 0","interpret":"true"},{"translate":"space.41","font":"default"},{"translate":"space.15","font":"default"},{"text":"\\uE005","font":"crafting"},{"translate":"space.-53","font":"default"},{"text":"\\uE006","font":"crafting"},{"translate":"space.-117","font":"default"}]'}
execute if score @s craft_slot_3 matches 1 if score @s slot_3_status matches 0 run data merge block 0 2 0 {Text1:'[{"nbt":"Text1","block":"0 2 0","interpret":"true"},{"text":"\\uE010","font":"crafting","color":"white"},{"translate":"space.15","font":"default"},{"text":"\\uE013","color":"dark_gray","font":"crafting"},{"translate":"space.-53","font":"default"},{"text":"\\uE014","color":"dark_gray","font":"crafting"},{"translate":"space.-117","font":"default"}]'}
execute if score @s craft_slot_3 matches 1 if score @s slot_3_status matches 1 run data merge block 0 2 0 {Text1:'[{"nbt":"Text1","block":"0 2 0","interpret":"true"},{"text":"\\uE010","font":"crafting","color":"white"},{"translate":"space.15","font":"default"},{"text":"\\uE013","font":"crafting"},{"translate":"space.-53","font":"default"},{"text":"\\uE014","font":"crafting"},{"translate":"space.-117","font":"default"}]'}
execute if score @s craft_slot_3 matches 2 if score @s slot_3_status matches 0 run data merge block 0 2 0 {Text1:'[{"nbt":"Text1","block":"0 2 0","interpret":"true"},{"text":"\\uE017","font":"crafting","color":"white"},{"translate":"space.15","font":"default"},{"text":"\\uE01A","color":"dark_gray","font":"crafting"},{"translate":"space.-53","font":"default"},{"text":"\\uE02D","color":"dark_gray","font":"crafting"},{"translate":"space.-117","font":"default"}]'}
execute if score @s craft_slot_3 matches 2 if score @s slot_3_status matches 1 run data merge block 0 2 0 {Text1:'[{"nbt":"Text1","block":"0 2 0","interpret":"true"},{"text":"\\uE017","font":"crafting","color":"white"},{"translate":"space.15","font":"default"},{"text":"\\uE01A","font":"crafting"},{"translate":"space.-53","font":"default"},{"text":"\\uE02D","font":"crafting"},{"translate":"space.-117","font":"default"}]'}
execute if score @s craft_slot_3 matches 3 if score @s slot_3_status matches 0 run data merge block 0 2 0 {Text1:'[{"nbt":"Text1","block":"0 2 0","interpret":"true"},{"text":"\\uE01D","font":"crafting","color":"white"},{"translate":"space.15","font":"default"},{"text":"\\uE020","color":"dark_gray","font":"crafting"},{"translate":"space.-53","font":"default"},{"text":"\\uE02D","color":"dark_gray","font":"crafting"},{"translate":"space.-117","font":"default"}]'}
execute if score @s craft_slot_3 matches 3 if score @s slot_3_status matches 1 run data merge block 0 2 0 {Text1:'[{"nbt":"Text1","block":"0 2 0","interpret":"true"},{"text":"\\uE01D","font":"crafting","color":"white"},{"translate":"space.15","font":"default"},{"text":"\\uE020","font":"crafting"},{"translate":"space.-53","font":"default"},{"text":"\\uE02D","font":"crafting"},{"translate":"space.-117","font":"default"}]'}
execute if score @s craft_slot_3 matches 4 if score @s slot_3_status matches 0 run data merge block 0 2 0 {Text1:'[{"nbt":"Text1","block":"0 2 0","interpret":"true"},{"text":"\\uE023","font":"crafting","color":"white"},{"translate":"space.15","font":"default"},{"text":"\\uE026","color":"dark_gray","font":"crafting"},{"translate":"space.-53","font":"default"},{"text":"\\uE02D","color":"dark_gray","font":"crafting"},{"translate":"space.-117","font":"default"}]'}
execute if score @s craft_slot_3 matches 4 if score @s slot_3_status matches 1 run data merge block 0 2 0 {Text1:'[{"nbt":"Text1","block":"0 2 0","interpret":"true"},{"text":"\\uE023","font":"crafting","color":"white"},{"translate":"space.15","font":"default"},{"text":"\\uE026","font":"crafting"},{"translate":"space.-53","font":"default"},{"text":"\\uE02D","font":"crafting"},{"translate":"space.-117","font":"default"}]'}
execute if score @s craft_slot_3 matches 5 if score @s slot_3_status matches 0 run data merge block 0 2 0 {Text1:'[{"nbt":"Text1","block":"0 2 0","interpret":"true"},{"text":"\\uE029","font":"crafting","color":"white"},{"translate":"space.15","font":"default"},{"text":"\\uE02C","color":"dark_gray","font":"crafting"},{"translate":"space.-53","font":"default"},{"text":"\\uE02D","color":"dark_gray","font":"crafting"},{"translate":"space.-117","font":"default"}]'}
execute if score @s craft_slot_3 matches 5 if score @s slot_3_status matches 1 run data merge block 0 2 0 {Text1:'[{"nbt":"Text1","block":"0 2 0","interpret":"true"},{"text":"\\uE029","font":"crafting","color":"white"},{"translate":"space.15","font":"default"},{"text":"\\uE02C","font":"crafting"},{"translate":"space.-53","font":"default"},{"text":"\\uE02D","font":"crafting"},{"translate":"space.-117","font":"default"}]'}
