function entities:bosses/globulous/attacks/attack2/testing

#summons
execute at @e[type=slime,tag=boss_1] run summon minecraft:armor_stand ~ ~1 ~ {Invulnerable:1b,Small:1b,Invisible:1b,NoBasePlate:1b,Motion:[-1.47,0.44,-0.57],Tags:["boss_1_boom"],ArmorItems:[{},{},{},{id:"minecraft:slime_block",Count:1b,tag:{display:{Name:'{"text":"Flammable Slimeball","color":"dark_red","italic":false}',Lore:['{"text":"Has a tendency to randomly explode","color":"gold","italic":false}']},HideFlags:63}}]}
execute at @e[type=slime,tag=boss_1] run summon minecraft:armor_stand ~ ~1 ~ {Invulnerable:1b,Small:1b,Invisible:1b,NoBasePlate:1b,Motion:[0.40,1.88,1.96],Tags:["boss_1_boom"],ArmorItems:[{},{},{},{id:"minecraft:slime_block",Count:1b,tag:{display:{Name:'{"text":"Flammable Slimeball","color":"dark_red","italic":false}',Lore:['{"text":"Has a tendency to randomly explode","color":"gold","italic":false}']},HideFlags:63}}]}
execute at @e[type=slime,tag=boss_1] run summon minecraft:armor_stand ~ ~1 ~ {Invulnerable:1b,Small:1b,Invisible:1b,NoBasePlate:1b,Motion:[-0.65,0.94,-1.889],Tags:["boss_1_boom"],ArmorItems:[{},{},{},{id:"minecraft:slime_block",Count:1b,tag:{display:{Name:'{"text":"Flammable Slimeball","color":"dark_red","italic":false}',Lore:['{"text":"Has a tendency to randomly explode","color":"gold","italic":false}']},HideFlags:63}}]}
execute at @e[type=slime,tag=boss_1] run summon minecraft:armor_stand ~ ~1 ~ {Invulnerable:1b,Small:1b,Invisible:1b,NoBasePlate:1b,Motion:[0.75,1.20,0.28],Tags:["boss_1_boom"],ArmorItems:[{},{},{},{id:"minecraft:slime_block",Count:1b,tag:{display:{Name:'{"text":"Flammable Slimeball","color":"dark_red","italic":false}',Lore:['{"text":"Has a tendency to randomly explode","color":"gold","italic":false}']},HideFlags:63}}]}
execute at @e[type=slime,tag=boss_1] run summon minecraft:armor_stand ~ ~1 ~ {Invulnerable:1b,Small:1b,Invisible:1b,NoBasePlate:1b,Motion:[-0.96,0.84,-0.73],Tags:["boss_1_boom"],ArmorItems:[{},{},{},{id:"minecraft:slime_block",Count:1b,tag:{display:{Name:'{"text":"Flammable Slimeball","color":"dark_red","italic":false}',Lore:['{"text":"Has a tendency to randomly explode","color":"gold","italic":false}']},HideFlags:63}}]}
execute at @e[type=slime,tag=boss_1] run summon minecraft:armor_stand ~ ~1 ~ {Invulnerable:1b,Small:1b,Invisible:1b,NoBasePlate:1b,Motion:[-1.66,0.85,0.40],Tags:["boss_1_boom"],ArmorItems:[{},{},{},{id:"minecraft:slime_block",Count:1b,tag:{display:{Name:'{"text":"Flammable Slimeball","color":"dark_red","italic":false}',Lore:['{"text":"Has a tendency to randomly explode","color":"gold","italic":false}']},HideFlags:63}}]}
execute at @e[type=slime,tag=boss_1] run summon minecraft:armor_stand ~ ~1 ~ {Invulnerable:1b,Small:1b,Invisible:1b,NoBasePlate:1b,Motion:[-0.70,1.21,0.43],Tags:["boss_1_boom"],ArmorItems:[{},{},{},{id:"minecraft:slime_block",Count:1b,tag:{display:{Name:'{"text":"Flammable Slimeball","color":"dark_red","italic":false}',Lore:['{"text":"Has a tendency to randomly explode","color":"gold","italic":false}']},HideFlags:63}}]}
execute at @e[type=slime,tag=boss_1] run summon minecraft:armor_stand ~ ~1 ~ {Invulnerable:1b,Small:1b,Invisible:1b,NoBasePlate:1b,Motion:[0.71,1.50,0.69],Tags:["boss_1_boom"],ArmorItems:[{},{},{},{id:"minecraft:slime_block",Count:1b,tag:{display:{Name:'{"text":"Flammable Slimeball","color":"dark_red","italic":false}',Lore:['{"text":"Has a tendency to randomly explode","color":"gold","italic":false}']},HideFlags:63}}]}
execute at @e[type=slime,tag=boss_1] run summon minecraft:armor_stand ~ ~1 ~ {Invulnerable:1b,Small:1b,Invisible:1b,NoBasePlate:1b,Motion:[-0.91,0.66,0.59],Tags:["boss_1_boom"],ArmorItems:[{},{},{},{id:"minecraft:slime_block",Count:1b,tag:{display:{Name:'{"text":"Flammable Slimeball","color":"dark_red","italic":false}',Lore:['{"text":"Has a tendency to randomly explode","color":"gold","italic":false}']},HideFlags:63}}]}
execute at @e[type=slime,tag=boss_1] run summon minecraft:armor_stand ~ ~1 ~ {Invulnerable:1b,Small:1b,Invisible:1b,NoBasePlate:1b,Motion:[0.66,1.35,-1.91],Tags:["boss_1_boom"],ArmorItems:[{},{},{},{id:"minecraft:slime_block",Count:1b,tag:{display:{Name:'{"text":"Flammable Slimeball","color":"dark_red","italic":false}',Lore:['{"text":"Has a tendency to randomly explode","color":"gold","italic":false}']},HideFlags:63}}]}
execute at @e[type=slime,tag=boss_1] run summon minecraft:armor_stand ~ ~1 ~ {Invulnerable:1b,Small:1b,Invisible:1b,NoBasePlate:1b,Motion:[1.85,0.72,0.24],Tags:["boss_1_boom"],ArmorItems:[{},{},{},{id:"minecraft:slime_block",Count:1b,tag:{display:{Name:'{"text":"Flammable Slimeball","color":"dark_red","italic":false}',Lore:['{"text":"Has a tendency to randomly explode","color":"gold","italic":false}']},HideFlags:63}}]}