# stop summon possiblity
scoreboard players set %1 singwoodsdun 1
scoreboard players set %2 singwoodsdun 1
scoreboard players set %3 singwoodsdun 1
scoreboard players set %4 singwoodsdun 1
scoreboard players set %5 singwoodsdun 1
scoreboard players set %6 singwoodsdun 1
scoreboard players set %7 singwoodsdun 1
scoreboard players set %8 singwoodsdun 1
scoreboard players set %9 singwoodsdun 1
scoreboard players set %10 singwoodsdun 1
scoreboard players set %11 singwoodsdun 1
scoreboard players set %12 singwoodsdun 1
scoreboard players set %13 singwoodsdun 1
scoreboard players set %14 singwoodsdun 1
scoreboard players set %15 singwoodsdun 1
scoreboard players set %16 singwoodsdun 1
scoreboard players set %17 singwoodsdun 1
scoreboard players set %18 singwoodsdun 1
scoreboard players set %19 singwoodsdun 1
scoreboard players set %20 singwoodsdun 1
scoreboard players set %21 singwoodsdun 1
scoreboard players set %22 singwoodsdun 1
scoreboard players set %23 singwoodsdun 1
scoreboard players set %24 singwoodsdun 1
scoreboard players set %25 singwoodsdun 1
scoreboard players set %26 singwoodsdun 1
scoreboard players set %27 singwoodsdun 1
scoreboard players set %28 singwoodsdun 1
scoreboard players set %29 singwoodsdun 1
scoreboard players set %30 singwoodsdun 1
scoreboard players set %31 singwoodsdun 1
scoreboard players set %32 singwoodsdun 1
scoreboard players set %33 singwoodsdun 1
scoreboard players set %34 singwoodsdun 1
scoreboard players set %35 singwoodsdun 1
scoreboard players set %36 singwoodsdun 1
scoreboard players set %37 singwoodsdun 1
scoreboard players set %38 singwoodsdun 1
scoreboard players set %39 singwoodsdun 1
scoreboard players set %40 singwoodsdun 1
scoreboard players set %41 singwoodsdun 1
scoreboard players set %42 singwoodsdun 1
scoreboard players set %43 singwoodsdun 1
scoreboard players set %44 singwoodsdun 1
scoreboard players set %45 singwoodsdun 1
scoreboard players set %46 singwoodsdun 1
scoreboard players set %47 singwoodsdun 1
scoreboard players set %48 singwoodsdun 1
scoreboard players set %49 singwoodsdun 1
scoreboard players set %50 singwoodsdun 1
scoreboard players set %51 singwoodsdun 1
scoreboard players set %52 singwoodsdun 1
scoreboard players set %53 singwoodsdun 1
scoreboard players set %54 singwoodsdun 1
scoreboard players set %55 singwoodsdun 1
scoreboard players set %56 singwoodsdun 1
scoreboard players set %57 singwoodsdun 1
scoreboard players set %58 singwoodsdun 1
scoreboard players set %59 singwoodsdun 1
scoreboard players set %60 singwoodsdun 1
scoreboard players set %61 singwoodsdun 1
scoreboard players set %62 singwoodsdun 1
scoreboard players set %63 singwoodsdun 1
scoreboard players set %64 singwoodsdun 1
scoreboard players set %65 singwoodsdun 1
scoreboard players set %66 singwoodsdun 1
scoreboard players set %67 singwoodsdun 1
scoreboard players set %68 singwoodsdun 1