scoreboard players enable @s null
scoreboard players enable @s pebble
scoreboard players enable @s chipped_rock
scoreboard players enable @s twig
scoreboard players enable @s feather
scoreboard players enable @s iron_ore
scoreboard players enable @s nickel_ore
scoreboard players enable @s nickel_nugget
scoreboard players enable @s iridium
scoreboard players enable @s bone
scoreboard players enable @s slime_ball
scoreboard players enable @s gelatin
scoreboard players enable @s regular_arrow
scoreboard players enable @s slimy_helmet
scoreboard players enable @s slimy_chestplate
scoreboard players enable @s slimy_leggings
scoreboard players enable @s slimy_boots
scoreboard players enable @s small_quiver
scoreboard players enable @s lesser_healing
scoreboard players enable @s healing
scoreboard players enable @s greater_healing
scoreboard players enable @s mystic_healing
scoreboard players enable @s pure_healing
scoreboard players enable @s crd_dragon_scale
scoreboard players enable @s dragon_scale
scoreboard players enable @s nchntd_drgn_scle
scoreboard players enable @s freeze
scoreboard players enable @s tinder