execute if score @s pebble matches 0.. run function engine:trigger/give/materials/misc/natural/pebble
execute if score @s chipped_rock matches 0.. run function engine:trigger/give/materials/misc/natural/chipped_rock
execute if score @s twig matches 0.. run function engine:trigger/give/materials/misc/natural/twig
execute if score @s feather matches 0.. run function engine:trigger/give/materials/mob_drops/passive/chicken/feather
execute if score @s iron_ore matches 0.. run function engine:trigger/give/materials/metals/iron/iron_ore
execute if score @s nickel_ore matches 0.. run function engine:trigger/give/materials/metals/nickel/nickel_ore
execute if score @s nickel_nugget matches 0.. run function engine:trigger/give/materials/metals/nickel/nickel_nugget
execute if score @s iridium matches 0.. run function engine:trigger/give/materials/metals/iridium/iridium_nugget
execute if score @s bone matches 0.. run function engine:trigger/give/materials/mob_drops/hostile/skeleton/bone
execute if score @s slime_ball matches 0.. run function engine:trigger/give/materials/mob_drops/hostile/bosses/globulous/slime_ball
execute if score @s gelatin matches 0.. run function engine:trigger/give/materials/mob_drops/hostile/bosses/globulous/gelatin
execute if score @s regular_arrow matches 0.. run function engine:trigger/give/gear/weapons/ranged/ammo/arrow/regular_arrow
execute if score @s slimy_helmet matches 0.. run function engine:trigger/give/gear/armor/slime_set/slimy_helmet
execute if score @s slimy_chestplate matches 0.. run function engine:trigger/give/gear/armor/slime_set/slimy_chestplate
execute if score @s slimy_leggings matches 0.. run function engine:trigger/give/gear/armor/slime_set/slimy_leggings
execute if score @s slimy_boots matches 0.. run function engine:trigger/give/gear/armor/slime_set/slimy_boots
execute if score @s small_quiver matches 0.. run function engine:trigger/give/accessories/ranged/quiver/small_quiver
execute if score @s lesser_healing matches 0.. run function engine:trigger/give/consumables/potions/healing/lesser_healing
execute if score @s healing matches 0.. run function engine:trigger/give/consumables/potions/healing/healing
execute if score @s greater_healing matches 0.. run function engine:trigger/give/consumables/potions/healing/greater_healing
execute if score @s mystic_healing matches 0.. run function engine:trigger/give/consumables/potions/healing/mystic_healing
execute if score @s pure_healing matches 0.. run function engine:trigger/give/consumables/potions/healing/pure_healing
execute if score @s crd_dragon_scale matches 0.. run function engine:trigger/give/consumables/potions/dragon_scale/crude_dragon_scale
execute if score @s dragon_scale matches 0.. run function engine:trigger/give/consumables/potions/dragon_scale/dragon_scale
execute if score @s nchntd_drgn_scle matches 0.. run function engine:trigger/give/consumables/potions/dragon_scale/enchanted_dragon_scale
