execute if score %launch sts_cannon matches 1 run function entities:bosses/sorass_the_sinner/attacks/cannon/launch/pattern/3/spawn/1
execute if score %launch sts_cannon matches 2 run function entities:bosses/sorass_the_sinner/attacks/cannon/launch/pattern/3/spawn/2
execute if score %launch sts_cannon matches 3 run function entities:bosses/sorass_the_sinner/attacks/cannon/launch/pattern/3/spawn/3
execute if score %launch sts_cannon matches 4 run function entities:bosses/sorass_the_sinner/attacks/cannon/launch/pattern/3/spawn/4
execute if score %launch sts_cannon matches 5 run function entities:bosses/sorass_the_sinner/attacks/cannon/launch/pattern/3/spawn/5
execute if score %launch sts_cannon matches 6 run function entities:bosses/sorass_the_sinner/attacks/cannon/launch/pattern/3/spawn/6
execute if score %launch sts_cannon matches 7 run function entities:bosses/sorass_the_sinner/attacks/cannon/launch/pattern/3/spawn/7
execute if score %launch sts_cannon matches 8 run function entities:bosses/sorass_the_sinner/attacks/cannon/launch/pattern/3/spawn/8
execute if score %launch sts_cannon matches 9 run function entities:bosses/sorass_the_sinner/attacks/cannon/launch/pattern/3/spawn/9