stopsound @a music music.creative
stopsound @a music music.credits
stopsound @a music music.end
stopsound @a music music.game
stopsound @a music music.menu
stopsound @a music music.nether.basalt_deltas
stopsound @a music music.nether.crimson_forest
stopsound @a music music.nether.nether_wastes
stopsound @a music music.nether.soul_sand_valley
stopsound @a music music.nether.warped_forest
stopsound @a music music.under_water
stopsound @a * ambient.cave