scoreboard objectives remove hp_container
scoreboard objectives remove hp_container2
scoreboard objectives remove mHP
scoreboard objectives remove ert
scoreboard objectives remove regeneration

scoreboard objectives remove X
scoreboard objectives remove Y
scoreboard objectives remove Z
scoreboard objectives remove X2
scoreboard objectives remove Y2
scoreboard objectives remove Z2
scoreboard objectives remove X_old
scoreboard objectives remove Y_old
scoreboard objectives remove Z_old
scoreboard objectives remove X_diff
scoreboard objectives remove Y_diff
scoreboard objectives remove Z_diff
scoreboard objectives remove in_motion