## Healing
give @s minecraft:snowball{CustomModelData:10000025,display:{Name:'{"text":"Lesser Healing Potion","color":"red","italic":false}',Lore:['{"text":"Marginally better than the school nurse.","color":"dark_gray","bold":false,"italic":false}','[{"text":""}]','[{"text":"Restores ","color":"white","bold":false,"italic":false},{"text":"15","color":"red","bold":true,"italic":false},{"text":"\\uE000","color":"white","italic":false}]','{"text":"COMMON","color":"gray","bold":true,"italic":false}']}} 1
give @s minecraft:snowball{CustomModelData:10000026,display:{Name:'{"text":"Healing Potion","color":"red","italic":false}',Lore:['{"text":"The world\'s most popular liquid bandage.","color":"dark_gray","bold":false,"italic":false}','[{"text":""}]','[{"text":"Restores ","color":"white","bold":false,"italic":false},{"text":"30","color":"red","bold":true,"italic":false},{"text":"\\uE000","color":"white","italic":false}]','{"text":"UNCOMMON","color":"green","bold":true,"italic":false}']}} 1
give @s minecraft:snowball{CustomModelData:10000027,display:{Name:'{"text":"Greater Healing Potion","color":"red","italic":false}',Lore:['{"text":"Like the healing potion, but greater.","color":"dark_gray","bold":false,"italic":false}','[{"text":""}]','[{"text":"Restores ","color":"white","bold":false,"italic":false},{"text":"75","color":"red","bold":true,"italic":false},{"text":"\\uE000","color":"white","italic":false}]','{"text":"UNCOMMON","color":"green","bold":true,"italic":false}']}} 1
give @s minecraft:snowball{CustomModelData:10000028,display:{Name:'{"text":"Mystic Healing Potion","color":"red","italic":false}',Lore:['{"text":"Nearly perfect in every way.","color":"dark_gray","bold":false,"italic":false}','[{"text":""}]','[{"text":"Restores ","color":"white","bold":false,"italic":false},{"text":"125","color":"red","bold":true,"italic":false},{"text":"\\uE000","color":"white","italic":false}]','{"text":"RARE","color":"blue","bold":true,"italic":false}']}} 1
give @s minecraft:snowball{CustomModelData:10000029,display:{Name:'{"text":"Pure Healing Potion","color":"aqua","italic":false}',Lore:['{"text":"One of the most precious brews","color":"dark_gray","bold":false,"italic":false}','{"text":"in history. Use it well.","color":"dark_gray","bold":false,"italic":false}','[{"text":""}]','[{"text":"Restores ","color":"white","bold":false,"italic":false},{"text":"250","color":"aqua","bold":true,"italic":false},{"text":"\\uE000","color":"white","italic":false}]','{"text":"LEGENDARY","color":"gold","bold":true,"italic":false}']}} 1

## Dragon Scale
give @s minecraft:snowball{CustomModelData:10000030,display:{Name:'{"text":"Crude Dragon Scale Potion","color":"white","italic":false}',Lore:['{"text":"Might cause you to look reptilian. Consult","color":"dark_gray","bold":false,"italic":false}','{"text":"your doctor for details.","color":"dark_gray","bold":false,"italic":false}','[{"text":"Duration: 10 Minutes","color":"gray","italic":false}]','[{"text":""}]','[{"text":"\\uE001","color":"white","bold":false,"italic":false},{"text":" +5% ","color":"white","bold":false,"italic":false},{"text":"Defense","color":"gray","italic":false}]','{"text":"COMMON","color":"gray","bold":true,"italic":false}']}} 1
give @s minecraft:snowball{CustomModelData:10000031,display:{Name:'{"text":"Dragon Scale Potion","color":"white","italic":false}',Lore:['{"text":"Skin becomes comparable to the ","color":"dark_gray","bold":false,"italic":false}','{"text":"strongest of stones.","color":"dark_gray","bold":false,"italic":false}','[{"text":"Duration: 10 Minutes","color":"gray","italic":false}]','[{"text":""}]','[{"text":"\\uE001","color":"white","bold":false,"italic":false},{"text":" +15% ","color":"white","bold":false,"italic":false},{"text":"Defense","color":"gray","italic":false}]','{"text":"RARE","color":"blue","bold":true,"italic":false}']}} 1
give @s minecraft:snowball{CustomModelData:10000032,display:{Name:'{"text":"Enchanted Dragon Scale Potion","color":"light_purple","italic":false}',Lore:['{"text":"Skin becomes impenetrable for a short time.","color":"dark_gray","bold":false,"italic":false}','[{"text":"Duration: 5 Minutes","color":"gray","italic":false}]','[{"text":""}]','[{"text":"\\uE001","color":"white","bold":false,"italic":false},{"text":" +35% ","color":"light_purple","bold":false,"italic":false},{"text":"Defense","color":"gray","italic":false}]','{"text":"LEGENDARY","color":"gold","bold":true,"italic":false}']},Enchantments:[{}]} 1